#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file for test enviroment.
 */
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'test');

return require __DIR__ . '/../../yii';
